### <a id='toc1_1_1_'></a>[NUMPY CREATE](#toc0_)

#### <a id='toc1_1_1_1_'></a>[Generate random array](#toc0_)

In [ ]:
import numpy as np

df = np.random.randint(1,40,5)
df

array([19,  3, 23, 15, 36])

#### <a id='toc1_1_1_2_'></a>[Get the array count](#toc0_)

In [ ]:
df.shape

(5,)

#### <a id='toc1_1_1_3_'></a>[Generate numpy array with Zeros](#toc0_)


In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### <a id='toc1_1_1_4_'></a>[Generate numpy array with Ones](#toc0_)


In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### <a id='toc1_1_1_5_'></a>[Generate numpy array with different numbers](#toc0_)


In [ ]:
a = np.random.randint(5,6,10)
b = np.ones(10) * 5
c = np.zeros(10) + 5

print(a,b,c)

[5 5 5 5 5 5 5 5 5 5] [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.] [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#### <a id='toc1_1_1_6_'></a>[Create an array of integers from 10 to 50](#toc0_)


In [ ]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### <a id='toc1_1_1_7_'></a>[Create an array of all the even integers from 10 to 50](#toc0_)


In [ ]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### <a id='toc1_1_1_8_'></a>[Creating a 3x3 matrix with values ranging from 0 to 8](#toc0_)

In [ ]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### <a id='toc1_1_1_9_'></a>[Create a 3x3 Identity matrix](#toc0_)

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### <a id='toc1_1_1_10_'></a>[Use numpy to generate a random number between 0 and 1](#toc0_)


In [ ]:
# rand - Always generate the value between 0 and 1 and it takes input as the number of values needed
np.random.rand(10)

array([0.11186221, 0.25486607, 0.02060812, 0.83867334, 0.75408707,
       0.77394211, 0.66280331, 0.22872452, 0.64252998, 0.27293603])

#### <a id='toc1_1_1_11_'></a>[Generate 25 random numbers samples from a standard normal distribution](#toc0_)


In [ ]:
np.random.randn(25)

array([-0.50943611,  0.14676784,  0.34820025, -1.05646241,  0.7133591 ,
       -0.74082042,  0.1798786 , -0.07168774, -1.11696895, -1.18629555,
       -1.53440112,  0.92839455,  0.68610668, -0.58253095,  0.63652136,
        1.65793298, -0.6293783 ,  1.63630885, -1.26194866,  0.62595753,
        0.68851952,  0.29845253,  0.80119621, -0.26564934,  1.54338754])

#### <a id='toc1_1_1_12_'></a>[Create the following matrix](#toc0_)


In [ ]:
np.linspace(0.01,1,100).reshape(10,10)
np.arange(0.01,1.01,.01).reshape(10,10)
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### <a id='toc1_1_1_13_'></a>[Create an array of 20 linearly spaced points between 0 and 1](#toc0_)

In [ ]:
# Create an array of 20 linearly spaced points between 0 and 1
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

#### <a id='toc1_1_1_14_'></a>[Create NXN Numpy Array - Indexing and Selection](#toc0_)

In [ ]:
import numpy as np

mat = np.arange(0,100).reshape(25,4)
mat

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59],
       [60, 61, 62, 63],
       [64, 65, 66, 67],
       [68, 69, 70, 71],
       [72, 73, 74, 75],
       [76, 77, 78, 79],
       [80, 81, 82, 83],
       [84, 85, 86, 87],
       [88, 89, 90, 91],
       [92, 93, 94, 95],
       [96, 97, 98, 99]])